# Generated by Django 3.2.9 on 2022-01-28 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climbing_ligue', '0002_edition'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Edition',
        ),
    ]
