# Generated by Django 3.2.9 on 2022-01-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbing_ligue', '0003_delete_edition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='points',
            field=models.CharField(max_length=5, verbose_name='Punktacja'),
        ),
    ]
