# Generated by Django 3.2.9 on 2022-01-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbing_ligue', '0004_alter_route_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_group',
            field=models.CharField(default='1', max_length=60, verbose_name='Grupa'),
        ),
        migrations.AlterField(
            model_name='route',
            name='edition',
            field=models.PositiveIntegerField(verbose_name='Edycja'),
        ),
        migrations.AlterField(
            model_name='route',
            name='points',
            field=models.FloatField(max_length=5, verbose_name='Punktacja'),
        ),
    ]
