# Generated by Django 3.2.9 on 2022-01-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbing_ligue', '0005_auto_20220129_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='edition',
            field=models.IntegerField(verbose_name='Edycja'),
        ),
    ]
