# Generated by Django 3.2.9 on 2022-02-01 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('climbing_ligue', '0010_user_routes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_routes',
            name='date_created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_routes',
            name='user_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='user_routes',
            name='user_routes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='climbing_ligue.route', verbose_name='User'),
        ),
    ]
