# Generated by Django 4.0.2 on 2022-02-16 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climbing_ligue', '0013_active_edition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='edition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='climbing_ligue.active_edition', verbose_name='Edycja'),
        ),
    ]
