# Generated by Django 4.0.2 on 2022-02-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbing_ligue', '0016_alter_user_group_edition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_group',
            name='edition',
            field=models.IntegerField(default=0, verbose_name='Edycja'),
        ),
    ]
