# Generated by Django 4.0.2 on 2022-02-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbing_ligue', '0017_alter_user_group_edition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_group',
            name='edition',
            field=models.IntegerField(verbose_name='Edycja'),
        ),
    ]
