# Generated by Django 4.0.2 on 2022-02-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbing_ligue', '0018_alter_user_group_edition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active_edition',
            name='current_edition',
            field=models.BooleanField(default=False, verbose_name='Bieżąca'),
        ),
    ]
