# Generated by Django 4.0.2 on 2022-02-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbing_ligue', '0019_alter_active_edition_current_edition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active_edition',
            name='edition',
            field=models.IntegerField(unique=True, verbose_name='Edycja'),
        ),
    ]
