# Generated by Django 4.0.2 on 2022-02-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbing_ligue', '0021_alter_route_edition_alter_user_group_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='edition',
            field=models.IntegerField(null=True, verbose_name='Edycja'),
        ),
    ]
