# Generated by Django 4.0.2 on 2022-02-21 20:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('climbing_ligue', '0022_alter_route_edition'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user_routes',
            unique_together={('user_name', 'user_routes')},
        ),
    ]
