# Generated by Django 4.0.2 on 2022-02-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbing_ligue', '0023_alter_user_routes_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Active_round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.CharField(max_length=5, verbose_name='Runda')),
                ('current_round', models.BooleanField(default=False, verbose_name='Bieżąca')),
            ],
        ),
    ]
